plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme

readme_index:
  enabled: false

remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - build_scripts
  - "*.bat"

markdown: kramdown
kramdown:
  parse_block_html: true

baseurl: "/CaTRoX_Classical/" 
url: "https://mayanez.github.io"

permalink: pretty

title: CaTRoX (Classical Edition)

aux_links:
  "View on GitHub":
    - "//github.com/theqwertiest/CaTRoX_Classical"

color_scheme: "dark"

footer_content: "CaTRoX (Classical Edition)"